feat: override include_watched w/ collection label
lostb1t/replex pull request #107
Opened 2023-11-24 14:22 UTC by luukleenders

- Added `include_watched` method to `MetaData` and `MediaContainer` models, looks at both env var and collection label.
- Added `HubWatchedTransform` and use it for `get_hubs_sections` and `transform_hubs_home` route handlers.
- Removed `WatchedFilter` from `transform_hubs_home` route handler, filtering is now handled by transform.
- Removed include_watched logic from `HubMixTransform` (this is now done in `HubWatchedTransform`).
- Improve include_watched logic in `LibraryMixTransform`, account for collection label and get correct size.

2023-11-24 14:43 UTC, lostb1t commented
thanks for this. Ill have look at the code this weekend.

One things is that the naming doesnt make sende anymore (thats my fault). Plex default is include and replex removes that. And adding REPLEX_INCLUDE_WATCHED as a label to exclude watched doesn’t make sense either 

So might be a good time to replace REPLEX_INCLUDE_WATCHED with REPLEX_EXCLUDE_WATCHED

Could you also change the readme for this and info for the new label?

2023-11-24 22:29 UTC, luukleenders commented
The name change makes sense, I've changed include to exclude - not sure if I did the 250 limit thing right though. 
Also updated the readme :)

2023-11-25 09:39 UTC, lostb1t requested changes
Just keep and adapt the pagination and its good togo.

2023-11-25 09:39 UTC, lostb1t commented on src/routes.rs
> -    if config.include_watched {
this can be adapted and kept. As it enables pagination (not supported when using excluded watched)

2023-11-25 09:39 UTC, lostb1t commented on src/routes.rs
> -    // in we dont remove watched then we dont need to limit
this can be adapted and kept. As it enables pagination (not supported when using excluded watched)

2023-11-25 11:54 UTC, luukleenders commented
I've tried to put pagination back but I should probably dive into how pagination actually works.

With `REPLEX_EXCLUDE_WATCHED=0` I get a maximum of 50 items back but the Plex ui won't load more when I scroll (my assumption is that it should?).
With `REPLEX_EXCLUDE_WATCHED=1` I get my entire collection back at once. 

Maybe I'm also just missing some context of different clients though, all I've tested on so far is the Plex web app.

2023-11-25 12:49 UTC, lostb1t commented
messy.

the gist is that when watched is excluded pagination wont work. So it returns the max of 250 per media type to counter that a little bit.

Wheb watched is included pagination should work. But in practice the clients are finniky. I think it doesn't work in the main branch properly either so this should be ok.

2023-11-25 13:18 UTC, lostb1t commented
@luukleenders pagination in default_transform should be put back again aswell

2023-11-25 17:44 UTC, luukleenders commented
Whoops, missed the default_transform - added it back.

2023-11-25 17:50 UTC, merged

2023-11-25 17:50 UTC, lostb1t commented
top, nogmaals dank hiervoor. Push gelijk een nieuwe release.

2023-11-25 18:03 UTC, lostb1t commented
:tada: This PR is included in version 0.20.0 :tada:

The release is available on [GitHub release](https://github.com/lostb1t/replex/releases/tag/0.20.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-11-26 09:08 UTC, luukleenders commented
> top, nogmaals dank hiervoor. Push gelijk een nieuwe release.

Oh NL haha nice!

Maar graag gedaan, was leuk om in te duiken en ik heb er zelf ook wat aan natuurlijk. Het is sowieso een hele mooie toevoeging aan Plex - als je nog andere puten hebt waar ik zou kunnen helpen dan laat maar weten :)